name: ci
on: [push, pull_request]
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.18.0'
      - name: Build
        run: go build ./...
      - name: Test
        run: go test ./... -v
      - name: Format
        run: gofmt -d . && [ -z "$(gofmt -l .)" ]
