name: ci
on: [push, pull_request]
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '^1.21.0'
      - name: Build
        run: go build ./...
      - name: Test
        run: go test ./... -v
      - name: Format
        run: gofmt -d . && [ -z "$(gofmt -l .)" ]
